---
ssl_cert_country: US
ssl_cert_state: California
ssl_cert_city: Santa Clara
ssl_cert_organization: IT
ssl_cert_cn: "{{ fqdn }}"
ssl_cert_lifetime: 365
ssl_directory: "/etc/myssl"
ssl_cert: "{{ ssl_directory }}/{{ fqdn }}.crt"
ssl_key: "{{ ssl_directory }}/{{ fqdn }}.key"
